language: node_js
  node_js:
    - 'stable'
  services:
    - mongodb
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-4.8
        - g++-4.8
  env:
    - CXX=g++-4.8
  sudo: required

  branches:
    only:
      -master
      -test_branch
  before_script: npm i
  script:
    - npm test
<<<<<<< HEAD
=======
 
>>>>>>> 270e337f4cf2977807d07564c69990cb4f2fe312
